name: Tests

defaults:
  run:
    working-directory: .

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 14
          distribution: 'adopt'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mvn --batch-mode test
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging